### ISSUE TITLE
Normalize key and type fields?

### ISSUE THREAD

**Issue by tmalsburg** [joostkremers/parsebib#1]
My understanding is that BibTeX keys and entry types are both case-insesitive.  Given that, would it make sense to normalize them in parsebib to have only lowercase letters?

**Comment by joostkremers** [comment]
Ebib used to do that (version 1.x), but then I decided to use the entry type and field definitions of `bibtex.el`, and those are mixed-case. Perhaps I should just go ahead and downcase them in Ebib as well...

**Comment by tmalsburg** [comment]
Hm, upon thinking about this a little more I believe that it's better to leave case untouched.  Some people have perferences about how their keys should look like and may be unhappy if they are converted to lowercase.
