### ISSUE TITLE
missing from melpa

### ISSUE THREAD

**Issue by VladimirAlexiev** [joostkremers/parsebib#15]
hi @joostkremers !
trying to `package-install` ebib or parsebib causes this error:
`package-install-from-archive: http://melpa.org/packages/parsebib-20210108.1525.el: Not found`.

BTW, thanks for your great work!

**Comment by joostkremers** [comment]
Hi, this error is usually caused by having outdated package info on your machine. If you update the package list (`M-x list-packages`), the error should go away.

**Comment by VladimirAlexiev** [comment]
thanks!
