### ISSUE TITLE
parsebib uses cl-loop without requiring cl-macs

### ISSUE THREAD

**Issue by swhahn** [joostkremers/parsebib#2]
If using a compiled version of parsebib by helm-bibtex, function parsebib-read-entry returns an error because cl-loop is not defined. This results in an empty list when calling helm-bibtex.

Inserting 
```elisp
(eval-when-compile
  (require 'cl-macs))
```
after 'require' at beginning of parsebib.el solved the problem.

**Comment by joostkremers** [comment]
Yup, you're right. Thanks for reporting, I pushed a fix.
