### ISSUE TITLE
New Release Tag?

### ISSUE THREAD

**Issue by yewscion** [joostkremers/parsebib#24]
Hello,

As mentioned in my [comment][1] on the relevant commit, the internal version number for this library has been bumped to 4.1, but there hasn't been a release tag created since 2021-12-08 with 3.1. Also, with the recent changes that merged some functionality from Ebib, the latest version of Ebib now relies on code from 4.1, even though it has not yet been 'released'.

Is there a way we could have a new release tag created, to communicate to others that there has been a major update?

[1]: https://github.com/joostkremers/parsebib/commit/185239020f878cfbe1036270e6c3d1026ba8f255

**Comment by joostkremers** [comment]
Yes, I should have done that right away. Should be taken care of now. Thanks for letting me know.

**Comment by yewscion** [comment]
Awesome, thanks for the quick response!
