### ISSUE TITLE
[Unexpected Behavior] Multiple Spaces Are Replaced with a Single Space

### ISSUE THREAD

**Issue by rennsax** [joostkremers/parsebib#33]
Hello, thanks for your contribution for Emacs! This package has become the fundamental library for other packages like citar. However, today I find it cannot parse my BibTeX correctly. After digging for a while, I find this function confusing:

https://github.com/joostkremers/parsebib/blob/ace9df707108b17759c004c7387655277122d4c1/parsebib.el#L496-L510

The problem is, my BibTeX exported by Zotera contains multiple spaces in the `file` field, for example:

```bib
@inproceedings{ahnIdentifyingCPUBottlenecks,
  title = {Identifying {{On-}}/{{Off-CPU Bottlenecks Together}} with {{Blocked Samples}} {\textbar} {{USENIX}}},
  shorttitle = {{{BCOZ}}},
  author = {Ahn, Minwoo and Han, Jeongmin and Kwon, Youngjin and Jeong, Jinkyu},
  urldate = {2024-10-09},
  langid = {english},
  file = {/Users/xxxx/Zotero/storage/ZJVUZD8F/Ahn et al. - Identifying On-Off-CPU Bottlenecks Together with Blocked Samples  USENIX.pdf}
}
```

But since the string is filtered by `parsebib--expand-strings`, the multiple spaces are replaced with a single space. As a result, it returns an incorrect filename, which causes further error like cannot find this file.

Is there any essential reason for replacing the strings? I just cannot understand.

**Comment by joostkremers** [comment]
`parsebib` basically has two modes: it can read `.bib` entries as-is, or it can post-process them into a form that is suitable for displaying to the user. Ebib uses the former, Citar uses the latter. 'Suitable for display' in this case means that TeX markup is removed or prettified, `@String` abberviations are expanded, cross-references are resolved and, indeed, multiple spaces are replaced with a single space.

Those changes are applied to all field values, except for the prettification of TeX markup, which does not apply to fields containing URIs (`file`, `url` and `doi`). Arguably, though, such fields should be exempt of any post-processing.

@bdarcus What do you think? Currently, we have the option `parsebib-clean-TeX-markup-excluded-fields`. I think it makes sense to refrain from applying the other prettifications to these fields as well. Or are you aware of any use-cases for which that would cause issues?

**Comment by bdarcus** [comment]
> @bdarcus What do you think? Currently, we have the option `parsebib-clean-TeX-markup-excluded-fields`. I think it makes sense to refrain from applying the other prettifications to these fields as well. Or are you aware of any use-cases for which that would cause issues?

What change are you suggesting on your end @joostkremers? That URL fields never get post-processed?

**Comment by joostkremers** [comment]
> What change are you suggesting on your end @joostkremers? That URL fields never get post-processed?

Yes, specifically the `url`, `doi` and `file` fields.

**Comment by bdarcus** [comment]
I can't see any problem with that.

**Comment by joostkremers** [comment]
I made the change. I have to admit, the code isn't very pretty and the API is not great, either, but it should work. @rennsax , could you see if things work for you now?

**Comment by rennsax** [comment]
I've tested and I think it now works correctly. Thanks for your work!

**Comment by rennsax** [comment]
Wait, I think it's citar's cache... It does not work at all.

https://github.com/joostkremers/parsebib/commit/3e2f46f55a83c0d45fc1fe4c5995e7119e687f0f#diff-683a7cddb641d9c7f09eed1e835b9d23d380a2d7ced337c1a6b86d59ce439383R779-R780

This two lines make `strings` to be `t`. `parsebib--parse-bib-value` accepts `strings` and emits error: "Wrong type argument: hash-table-p, t"

**Comment by rennsax** [comment]
You may want this:
```diff
-                 (strings (and strings
-                               (not (member-ignore-case field parsebib-postprocessing-excluded-fields))))
+                 (strings (unless (member-ignore-case field parsebib-postprocessing-excluded-fields) strings))
```

But it's incorrect too. In `parsebib--parse-bib-value`, the values are simply joined with `#`, but the surrounding curly brackets are not removed.
```elisp
    (setq res (if strings
                  (string-join (parsebib--expand-strings (nreverse res) strings))
                (string-join (nreverse res) " # ")))
```

**Comment by rennsax** [comment]
To test with citar, remember to evoke the cache:

```elisp
(setq citar-cache--bibliographies (make-hash-table :test 'equal))
```

**Comment by rennsax** [comment]
> If no post-processing takes place, braces _should_ be kept.

I mean,
```bibtex
@inproceedings{ahnIdentifyingCPUBottlenecks,
  title = {Identifying {{On-}}/{{Off-CPU Bottlenecks Together}} with {{Blocked Samples}} {\textbar} {{USENIX}}},
  shorttitle = {{{BCOZ}}},
  author = {Ahn, Minwoo and Han, Jeongmin and Kwon, Youngjin and Jeong, Jinkyu},
  urldate = {2024-10-09},
  langid = {english},
  file = {/Users/xxxx/Zotero/storage/ZJVUZD8F/Ahn et al. - Identifying On-Off-CPU Bottlenecks Together with Blocked Samples  USENIX.pdf}
}
```

the value of `file` will be `{/Users/xxxx/Zotero/storage/ZJVUZD8F/Ahn et al. - Identifying On-Off-CPU Bottlenecks Together with Blocked Samples  USENIX.pdf}`. Is that right?

**Comment by joostkremers** [comment]
> the value of `file` will be `{/Users/xxxx/Zotero/storage/ZJVUZD8F/Ahn et al. - Identifying On-Off-CPU Bottlenecks Together with Blocked Samples USENIX.pdf}`. Is that right?

Ah, I see what you mean... I guess the answer is yes and no. Yes, because that is how parsebib is designed to work. No. because for Citar's use case, it is not practical...

This is where the bad design I alluded to earlier comes in... With a better design, it would be an easy fix. As it stands, we'll need another kludge... :sob:

**Comment by joostkremers** [comment]
Well, I ended up reverting the change I made in 3e2f46f. Getting everything to work right would have required stacking kludge upon kludge... Instead, I decided to just not collapse multiple spaces into one. Newlines are still replaced with a space, (as are tabs and form feeds, though I doubt they'll occur very often in `.bib` files :thinking:) but multiple spaces are kept as-is.

Please let me know if this solves your problem, hopefully without causing other issues...

**Comment by rennsax** [comment]
I think it now works for citar's use case. Hope this change does not break other things...

**Comment by joostkremers** [comment]
> I think it now works for citar's use case. Hope this change does not break other things...

 So do I... But I don't see how it could. I reverted all changes I made after you posted your issue and ended up only changing the one thing you really complained about, which is that multiple spaces are collapsed into one. That is really just a minor change and it's a cosmetic one. Well, mostly cosmetic of course, except in *your* use case... :smile: 

I'm going to keep this issue open, because if I find some time, I'd really like to refactor the code so I can implement my original solution.

**Comment by joostkremers** [comment]
Well, I pushed some changes that make it possible to collapse whitespace in all fields except the file, URL and DOI fields. I also added some tests to make sure things stay that way. It's not the bigger refactoring that I envisaged, but it's also not as hacky as I had feared initially. (I tried the refactoring and it works, but I ultimately decided against that approach.)

Let me know if you run into any issues.

**Comment by rennsax** [comment]
Till now it works fine. At least the culprit `file` field can be parsed correctly.

<img width="664" alt="image" src="https://github.com/user-attachments/assets/5575387c-eb5d-46db-8e4e-23c8ad53d315">

I'll keep using it and report possible issues.

**Comment by joostkremers** [comment]
I'm closing this issue now. If you run into problems, feel free to reopen it or create a new issue.

Thanks for reporting this and testing the various solution attempts. :slightly_smiling_face:
