### ISSUE TITLE
What can we expect if we round-trip a bibliography file?

### ISSUE THREAD

**Issue by rpgoldman** [joostkremers/parsebib#9]
The reason I ask is for interaction with revision control systems like git and subversion.  If bib databases are dumped into, for example, lexicographically-sorted `.bib` files, then RCSes will be able to accurately identify diffs.  But if they are dumped in an arbitrary order, then the bib files will effectively be binary files from the standpoint of RCSes (or, indeed, anything that relies on `diff`).

**Comment by joostkremers** [comment]
The order in which entries are saved back to the `.bib` file, (which is an Ebib issue, BTW, not a parsebib issue), is customisable, see the section [Sorting the `.bib` file](http://joostkremers.github.io/ebib/ebib-manual.html#sorting-the-.bib-file) in the Ebib manual. The fields of an entry are stored as an alist and are saved in the same order in which they are read.

If you use Ebib to modify a file that was saved with Ebib, the file should be identical to the previous version except for the changes you made. I don't actually have my `.bib` files under version control (I should, but I don't... :smiley:) but I'd consider it a bug if Ebib interfered with version control on its own files.

Things are different with files modified outside of Ebib, or files first opened in Ebib, though. Ebib doesn't know the order of entries in a `.bib` file, so when the file is saved, entries may end up in a different order.

There are also smaller issues, such as that Ebib uses braces `{}` to delimit entries and fields, not parentheses `()` or double quotes `""`. `@Comments` are all saved to the top of the file and all `@Preamble` definitions are collapsed into one. So those things will turn up as diffs.
